#!/usr/bin/env bash
#The script is instaling and configuring HAproxy on my `lb-01` server.
sudo apt-get update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get update
sudo apt-get install haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

echo "defaults
	log	global
	option	httplog
frontend web-server
	bind *:80
	mode    http
	default_backend web-servers
	
backend web-servers
	balance	roundrobin
	server 48630-web-01 34.202.158.186:80 check
	server 48630-web-02 52.91.144.181:80 check" >> /etc/haproxy/haproxy.cfg

#Enable haproxy to be managed via init script
systemctl enable haproxy

#start haproxy
systemctl start haproxy
