#!/usr/bin/env bash
# configure a load-balancing server

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy=2.4.\*

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 976-web-01 34.202.158.186
	server 976-web-02 18.207.236.203" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
